apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-run-
spec:
  serviceAccountName: build-bot
  params:
  - name: source-repo
    value: https://github.com/EmLRans/emily-ransley-docker-repo
  - name: image-repo
    value: quay.io/em_l_rans_ibm/express-sample-app
  pipelineRef:
    name: buildah
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce